#!/bin/bash

rm -f result_sat_small

for f in extracted-constraints/sat/small/*.ml; do
    echo "$f
    "
    echo $f >> result_sat_small
    (/usr/bin/time ./$f.out) 2>&1 |  cat >> result_sat_small
done

rm -f result_unsat_small

for f in extracted-constraints/unsat/small/*.ml; do
    echo "$f
    "
    echo $f >> result_unsat_small
    (/usr/bin/time ./$f.out) 2>&1 |  cat >> result_unsat_small
done


rm -f result_sat_big

for f in extracted-constraints/sat/big/*.ml; do
    echo "$f
    "
    echo $f >> result_sat_big
    (/usr/bin/time ./$f.out) 2>&1 |  cat >> result_sat_big
done

rm -f result_unsat_big

for f in extracted-constraints/unsat/big/*.ml; do
    echo "$f
    "
    echo $f >> result_unsat_big
    (/usr/bin/time ./$f.out) 2>&1 |  cat >> result_unsat_big
done

