#!/bin/sh
# File generated by ocamlbuild

cd /Users/kanshl/workspace/str-calculus/model/ORI2CAVA

rm -f main.cmi
rm -f main.cmo
rm -f ori.cmi
rm -f ori.cmo
rm -f ori.ml
rm -f ori.mli
rm -f orilex.cmi
rm -f orilex.cmo
rm -f orilex.ml
rm -f trans.cmi
# Also clean the script itself
rm -f /Users/kanshl/workspace/str-calculus/model/ORI2CAVA/_build/sanitize.sh
