#!/bin/bash

for f in extracted-constraints/test/*.smt2; do
    ORI2CAVA/ori2cava $f
done

for f in extracted-constraints/test/*.ml; do
    ocamlc -I forward_analysis/zarith -o test.cmo -c $f
    ocamlc -o auto forward_analysis/zarith/zarith.cma forward_analysis/Automata_lib.cmo forward_analysis/Forward.cmo test.cmo
    ./auto
done


#rm -f tests/*a
