#!/bin/bash

rm -f result

for f in tests/*.ml; do
        ocamlc -I zarith -c Automata_lib.ml
	ocamlc -I zarith -c Automata.ml
	ocamlc -o test.cmo -c $f
	ocamlc -o auto zarith/zarith.cma Automata_lib.cmo Automata.cmo test.cmo
        echo $f >> result
	echo "
	"
	(/usr/bin/time ./auto) 2>&1 |  cat >> result
done

rm *.cmi
rm *.cmo
rm auto
